# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{mailcatcher}
  s.version = "0.2.4"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Samuel Cochran"]
  s.date = %q{2011-05-10}
  s.default_executable = %q{mailcatcher}
  s.description = %q{      MailCatcher runs a super simple SMTP server which catches any
      message sent to it to display in a web interface. Run
      mailcatcher, set your favourite app to deliver to
      smtp://127.0.0.1:1025 instead of your default SMTP server,
      then check out http://127.0.0.1:1080 to see the mail.
}
  s.email = %q{sj26@sj26.com}
  s.executables = ["mailcatcher"]
  s.extra_rdoc_files = [
    "LICENSE",
    "README.md"
  ]
  s.files = [
    "LICENSE",
    "README.md",
    "Rakefile",
    "VERSION",
    "bin/mailcatcher",
    "contrib/mailcatcherd.bash",
    "lib/mail_catcher.rb",
    "lib/mail_catcher/events.rb",
    "lib/mail_catcher/mail.rb",
    "lib/mail_catcher/smtp.rb",
    "lib/mail_catcher/web.rb",
    "public/javascripts/application.js",
    "public/javascripts/jquery.js",
    "public/stylesheets/application.css",
    "views/index.haml"
  ]
  s.homepage = %q{http://github.com/sj26/mailcatcher}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.6.2}
  s.summary = %q{Runs an SMTP server, catches and displays email in a web interface.}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<eventmachine>, [">= 0"])
      s.add_runtime_dependency(%q<mail>, [">= 0"])
      s.add_runtime_dependency(%q<i18n>, [">= 0"])
      s.add_runtime_dependency(%q<sqlite3-ruby>, [">= 0"])
      s.add_runtime_dependency(%q<thin>, [">= 0"])
      s.add_runtime_dependency(%q<skinny>, [">= 0.1.2"])
      s.add_runtime_dependency(%q<sinatra>, [">= 0"])
      s.add_runtime_dependency(%q<haml>, [">= 0"])
      s.add_runtime_dependency(%q<json>, [">= 0"])
    else
      s.add_dependency(%q<eventmachine>, [">= 0"])
      s.add_dependency(%q<mail>, [">= 0"])
      s.add_dependency(%q<i18n>, [">= 0"])
      s.add_dependency(%q<sqlite3-ruby>, [">= 0"])
      s.add_dependency(%q<thin>, [">= 0"])
      s.add_dependency(%q<skinny>, [">= 0.1.2"])
      s.add_dependency(%q<sinatra>, [">= 0"])
      s.add_dependency(%q<haml>, [">= 0"])
      s.add_dependency(%q<json>, [">= 0"])
    end
  else
    s.add_dependency(%q<eventmachine>, [">= 0"])
    s.add_dependency(%q<mail>, [">= 0"])
    s.add_dependency(%q<i18n>, [">= 0"])
    s.add_dependency(%q<sqlite3-ruby>, [">= 0"])
    s.add_dependency(%q<thin>, [">= 0"])
    s.add_dependency(%q<skinny>, [">= 0.1.2"])
    s.add_dependency(%q<sinatra>, [">= 0"])
    s.add_dependency(%q<haml>, [">= 0"])
    s.add_dependency(%q<json>, [">= 0"])
  end
end

