steps:
  - label: ":github: CI"
    key: "github-actions-ci"
    agents:
      queue: hosted
    plugins:
      - github-actions#v0.13.0:
          workflow: .github/workflows/ci.yml
          source-ref: "eb736b2af19cfc564d9e1046d1b35d59e59554cb"
          experimental-runner-user: true
          runners:
            - runs-on: ubuntu-latest
              queue: hosted
            - runs-on: macos-latest
              queue: macos-medium
