#!/usr/bin/env bash

set -euo pipefail

if [[ "${BUILDKITE_PULL_REQUEST:-false}" == "false" ]]; then
  exit 0
fi

git fetch --no-tags origin \
  "+refs/heads/${BUILDKITE_PULL_REQUEST_BASE_BRANCH}:refs/remotes/origin/${BUILDKITE_PULL_REQUEST_BASE_BRANCH}" \
  "+refs/pull/${BUILDKITE_PULL_REQUEST}/merge:refs/remotes/origin/pull/${BUILDKITE_PULL_REQUEST}/merge"
