#!/bin/bash

set -e # exit if any commands returns a non-zero exit code.

cd "$(dirname "$0")/.." # cd into project root.

./scripts/setup

bundle exec rake assets
bundle exec mailcatcher --ip 0.0.0.0 --http-port 80 --smtp-port 25 --foreground $@
